# Generated by Django 4.2 on 2023-04-17 16:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_address_zip_code"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="price",
            new_name="unit_price",
        ),
    ]
