# Generated by Django 4.2 on 2023-04-17 16:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_rename_price_product_unit_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="birthdate",
            new_name="birth_date",
        ),
    ]
