# Generated by Django 4.2 on 2023-04-20 16:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0006_reviews"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("cart", "product")},
        ),
    ]
